{{- if not .Values.syncv3.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sliding-sync-env
data:
  SYNCV3_SERVER: {{ .Values.syncv3.server | b64enc | quote }}
  SYNCV3_DB: {{ .Values.syncv3.db | b64enc | quote }}
  SYNCV3_SECRET: {{ .Values.syncv3.secret | b64enc | quote }}
  SYNCV3_BINDADDR: {{ .Values.syncv3.bindaddr | b64enc | quote }}
  SYNCV3_TLS_CERT: {{ .Values.syncv3.tlsCert | b64enc | quote }}
  SYNCV3_TLS_KEY: {{ .Values.syncv3.tlsKey | b64enc | quote }}
  SYNCV3_PPROF: {{ .Values.syncv3.pprof | b64enc | quote }}
  SYNCV3_PROM: {{ .Values.syncv3.prom | b64enc | quote }}
  SYNCV3_OTLP_URL: {{ .Values.syncv3.otlpUrl | b64enc | quote }}
  SYNCV3_OTLP_USERNAME: {{ .Values.syncv3.otlpUsername | b64enc | quote }}
  SYNCV3_OTLP_PASSWORD: {{ .Values.syncv3.otlpPassword | b64enc | quote }}
  SYNCV3_SENTRY_DSN: {{ .Values.syncv3.sentryDsn | b64enc | quote }}
  SYNCV3_LOG_LEVEL: {{ .Values.syncv3.logLevel | b64enc | quote }}
  SYNCV3_MAX_DB_CONN: {{ .Values.syncv3.maxDbConn | b64enc | quote }}

{{- end }}
